#!/usr/bin/env python3
"""Deterministically generate synthetic SESSION 18 fixtures and the field matrix."""
import copy,csv,hashlib,json,pathlib
R=pathlib.Path(__file__).resolve().parents[1]
def canon(v): return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def h(v): return hashlib.sha256(canon(v)).hexdigest()
def save(path,obj):
 p=R/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
payload={'synthetic':True,'mint':'So11111111111111111111111111111111111111112'}; dig=h(payload); ts='2026-08-21T00:00:00.000000Z'; sig='3'*88
base={
 'contract_name':'event-envelope','contract_version':'1.0.0','event_id':'urn:dex-ai:event:'+'1'*32,'event_type':'MINT_INITIALIZED','event_version':'1.0.0','event_domain':'CHAIN','event_stage':'RAW','producer_name':'synthetic-collector','producer_version':'1.0.0',
 'source_id':'urn:dex-ai:source:solana-test','source_type':'SYNTHETIC','source_record_id':'synthetic-001','subject_ref':'urn:dex-ai:entity:token:canonical:So11111111111111111111111111111111111111112','related_entity_refs':[],
 'event_time':ts,'observed_at':ts,'ingested_at':'2026-08-21T00:00:00.100000Z','available_at':'2026-08-21T00:00:00.200000Z','ordering_key':'urn:dex-ai:ordering:synthetic:test','ordering_position':'source:00000000000000000001:synthetic-001',
 'idempotency_key':'sha256:'+h({'source':'synthetic-001'}),'correlation_id':'urn:dex-ai:correlation:'+'2'*32,'causation_event_id':None,
 'trace_context':{'trace_id':'3'*32,'span_id':'4'*16,'parent_span_id':None,'trace_flags':'01'},'payload':payload,'payload_hash':'sha256:'+dig,
 'raw_ref':{'artifact_id':'urn:dex-ai:raw:'+'5'*64,'locator':'ipfs://bafybeigdyrsyntheticartifact','content_hash':'sha256:'+'6'*64,'content_type':'application/json','captured_at':ts,'environment':'test','availability':'AVAILABLE'},
 'verification_status':'VERIFIED','finality_status':'NOT_APPLICABLE','provenance':{'origin_kind':'ORIGINAL','source_identity':'urn:dex-ai:source:solana-test','collector':{'name':'synthetic-collector','version':'1.0.0'},'collection_method':'POLL','observed_at':ts,'environment':'test','normalizer':None,'transform_chain':[],'parent_artifact_refs':[],'replay_lineage':None},
 'quality_flags':[],'schema_versions':{'envelope':'1.0.0','payload':'1.0.0','normalizer':None},'data_classification':'PUBLIC','retention_class':'RAW_EVIDENCE_365D','integrity':{'algorithm':'SHA-256','canonicalization':'RFC8785-JCS-PROFILE','encoding':'UTF-8','scope':'payload','digest':dig,'status':'VERIFIED','verified_at':'2026-08-21T00:00:00.150000Z'},'admission_status':'AVAILABLE','execution_mode':'LIVE','replay':None}
valid={'minimal-raw-on-chain':base,'full-raw-on-chain':dict(base,source_type='SOLANA_RPC',block_slot=123456789,block_time=ts,tx_signature=sig,instruction_index=0,inner_index=0,ordering_position=f'chain:123456789:{sig}:0:0'),'root-event':base,'empty-related-refs':base,'live-event':base}
for name,stage in [('minimal-normalized','NORMALIZED'),('full-normalized','NORMALIZED'),('minimal-system','SYSTEM')]:
 e=copy.deepcopy(base); e['event_id']='urn:dex-ai:event:'+hashlib.md5(name.encode()).hexdigest(); e['event_stage']=stage; e['causation_event_id']=base['event_id']; e['provenance']['origin_kind']='NORMALIZED' if stage=='NORMALIZED' else 'DERIVED'; e['raw_ref']=None; valid[name]=e
re=copy.deepcopy(base); re['event_id']='urn:dex-ai:event:'+'7'*32; re['execution_mode']='REPLAY'; re['provenance']['origin_kind']='REPLAYED'; re['provenance']['replay_lineage']='urn:dex-ai:replay:'+'8'*32; re['replay']={'replay_id':'urn:dex-ai:replay:'+'8'*32,'replay_run_id':'urn:dex-ai:replay-run:'+'9'*32,'cutoff_at':'2026-08-21T00:01:00.000000Z','dataset_ref':'urn:dex-ai:dataset:'+'a'*32,'snapshot_ref':'urn:dex-ai:snapshot:'+'b'*64,'source_artifact_versions':{'source':'1.0.0'},'schema_versions':{'envelope':'1.0.0'},'policy_versions':{'admission':'1.0.0'},'code_version':'git:'+'c'*40,'environment':'test','seed':42}; valid['replay-event']=re
for field,name,kind in [('corrects_event_id','corrected-event','CORRECTED'),('supersedes_event_id','superseding-event','DERIVED'),('revokes_event_id','revocation-event','DERIVED')]:
 e=copy.deepcopy(base); e['event_id']='urn:dex-ai:event:'+hashlib.md5(name.encode()).hexdigest(); e[field]=base['event_id']; e['provenance']['origin_kind']=kind; valid[name]=e
for n,e in valid.items(): save(f'fixtures/session18/valid/{n}.json',e)
def bad(name,fn): e=copy.deepcopy(base); fn(e); save(f'fixtures/session18/invalid/{name}.json',e)
bad('missing-required-field',lambda e:e.pop('event_id')); bad('illegal-null',lambda e:e.__setitem__('event_id',None)); bad('empty-identifier',lambda e:e.__setitem__('event_id','')); bad('invalid-identifier',lambda e:e.__setitem__('event_id','evt-1')); bad('invalid-enum',lambda e:e.__setitem__('event_stage','BAD')); bad('unknown-top-level',lambda e:e.__setitem__('mystery',1)); bad('invalid-timestamp',lambda e:e.__setitem__('observed_at','not-time')); bad('non-utc-timestamp',lambda e:e.__setitem__('observed_at','2026-08-21T03:00:00.000000+03:00')); bad('wrong-fractional-precision',lambda e:e.__setitem__('observed_at','2026-08-21T00:00:00Z')); bad('impossible-timestamp-order',lambda e:e.__setitem__('ingested_at','2026-08-20T00:00:00.000000Z')); bad('invalid-solana-signature',lambda e:e.update(source_type='SOLANA_RPC',block_slot=1,block_time=ts,tx_signature='bad',instruction_index=0,inner_index=0)); bad('invalid-block-slot',lambda e:e.update(source_type='SOLANA_RPC',block_slot=-1,block_time=ts,tx_signature=sig,instruction_index=0,inner_index=0)); bad('negative-instruction-index',lambda e:e.update(source_type='SOLANA_RPC',block_slot=1,block_time=ts,tx_signature=sig,instruction_index=-1,inner_index=0)); bad('invalid-trace-id',lambda e:e['trace_context'].__setitem__('trace_id','0'*32)); bad('payload-redefines-envelope',lambda e:e['payload'].__setitem__('event_id','evil')); bad('unsafe-raw-reference',lambda e:e['raw_ref'].__setitem__('locator','s3://bucket/../secret?token=x')); bad('hash-mismatch',lambda e:e['payload'].__setitem__('synthetic',False)); bad('unsupported-hash-algorithm',lambda e:e['integrity'].__setitem__('algorithm','MD5')); bad('unsupported-contract-version',lambda e:e.__setitem__('contract_version','2.0.0')); bad('available-before-verification',lambda e:e.__setitem__('verification_status','UNVERIFIED')); bad('quarantined-with-available-at',lambda e:e.update(admission_status='QUARANTINED',quarantine_reasons=['INTEGRITY_MISMATCH'])); bad('multiple-change-references',lambda e:e.update(corrects_event_id=base['event_id'],revokes_event_id=base['event_id'])); bad('future-data-replay',lambda e:e.update(execution_mode='REPLAY',replay=copy.deepcopy(re['replay']),available_at='2026-08-21T00:02:00.000000Z'))
dup=copy.deepcopy(base); save('fixtures/session18/classification/duplicate-event-id.json',dup); dup2=copy.deepcopy(base); dup2['event_id']='urn:dex-ai:event:'+'d'*32; save('fixtures/session18/classification/duplicate-idempotency-key.json',dup2)
late=copy.deepcopy(base); late['observed_at']='2026-08-21T00:10:00.000000Z'; late['event_time']='2026-08-21T00:00:00.000000Z'; late['quality_flags']=['LATE']; save('fixtures/session18/classification/late-event.json',late)
ooo=copy.deepcopy(base); ooo['ordering_position']='source:00000000000000000000:synthetic-000'; ooo['quality_flags']=['OUT_OF_ORDER']; save('fixtures/session18/classification/out-of-order-event.json',ooo)
schema=json.loads((R/'schemas/events/event-envelope/1.0.0/schema.json').read_text()); fields=list(schema['properties']); required=set(schema['required'])
cols=['Field Name','Meaning','JSON Type','Requiredness','Nullable','Empty Allowed','Format or Enum','Conditional Requiredness','Normative Source','Owner','Security Classification','Retention Classification','Integrity Participation','Valid Example','Invalid Example','Admission Interaction','Replay Interaction','Test']
with (R/'metadata/event-envelope-field-source-matrix.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=cols); w.writeheader()
 for x in fields:
  p=schema['properties'][x]; typ=p.get('type','ref/union/enum/const'); w.writerow({'Field Name':x,'Meaning':f'Executable semantics defined by Event Envelope v1 §Field Closure: {x}','JSON Type':typ,'Requiredness':'Required' if x in required else 'Optional non-null when present','Nullable':'Yes only when schema union includes null' if 'oneOf' in p else 'No','Empty Allowed':'Only related_entity_refs may be empty','Format or Enum':p.get('pattern') or p.get('$ref') or json.dumps(p.get('enum') or p.get('const')),'Conditional Requiredness':'See JSON Schema allOf','Normative Source':'SESSION 18 semantic closure constrained by SESSION 00-16','Owner':'Basel Atta','Security Classification':'INTERNAL','Retention Classification':'EVENT_730D','Integrity Participation':'payload only' if x=='payload' else 'Not in payload digest','Valid Example':'session18/valid','Invalid Example':'session18/invalid','Admission Interaction':'Schema and semantic validation','Replay Interaction':'cutoff enforced','Test':'tooling/validate/runner.py'})
print('SESSION18_FIXTURES_BUILT',len(valid),23)
